### ISSUE TITLE
vandy.csv stops in 2004

### ISSUE THREAD

**Issue by moos** [notnews/vandy_tv_news_abstracts#1]
Hi -- vandy.csv (v3) hosted on Harvard Dataverse site seems to stop at 2004.  The last item is:
```
"(Studio: Carol Lin) Report introduced.(Atlanta: Morgan Neill) The rescue of 16-year-old Muhammet Kalem†from the rubble of an apartment building that collapsed 6 days ago in Istanbul, Turkey, featured; scenes shown. [Father Ahmet KALEM†{thru translator} – reacts to his son’s rescue.]",,748152,"Lin, Carol;spelling, Morgan Neal‡",09:43:40 pm-09:45:30 pm,Turkey / Building Collapse,"Sunday, Feb 08, 2004",about 1 hour,CNN Evening News
```
I was wondering if the remaining items up to the present (or say late 2019) are available in CSV format.

**Comment by soodoku** [comment]
I don't think that's true. This project uses that data: https://github.com/notnews/notwork_news

**Comment by soodoku** [comment]
confirmed. not true.

**Comment by moos** [comment]
Upon further inspection, it seems there is no order to the CSV file entries.  Although the last item in the file is what I pasted above, the file does contain entries up to Dec. 2019.
